### ISSUE TITLE
example ppx rewriter not compatible with dune "No ppx driver were found" error

### ISSUE THREAD

**Issue by aryx** [let-def/migrate-parsetree#102]
I've tried to use the examples in examples/omp_ppx_here/ to build my own ppx rewriter.
However after a make install in this directory, I tried to use the ppx in one of my project using dune
with
 (preprocess (pps omp_ppx_here))

but then I got the following error:
ile "matching/dune", line 4, characters 13-31:
4 |  (preprocess (pps omp_ppx_here))
                 ^^^^^^^^^^^^^^^^^^
Error: No ppx driver were found. It seems that omp_ppx_here is not compatible
with Dune. Examples of ppx rewriters that are compatible with Dune are ones
using ocaml-migrate-parsetree, ppxlib or ppx_driver.
Makefile:3: recipe for target 'all' failed

What do I need to get omp_ppx_here usable from dune?

**Comment by ghost** [comment]
Hmm, these examples are quite old. We could port them to Dune, though we are preparing a 2.0.0 release of ocaml-migrate-parsetree that will drop the driver part. You should use [ppxlib](https://github.com/ocaml-ppx/ppxlib) for new ppx rewriters.

**Comment by aryx** [comment]
Ok, thx!
