### ISSUE TITLE
Where are we on 4.05+beta compatibility?

### ISSUE THREAD

**Issue by gasche** [let-def/migrate-parsetree#11]
The README still mentions 4.05 as trunk. Now that 4.05 has been branched in preparation for a release, those are two distinct branches. Could you update the text and maybe clarify that 4.05 support is feature-complete with respect to the beta(s)?

Alain Frisch mentioned that this tool should be recommended for ppx authors for stability/compatibility. I am planning to mention it during the 4.05 release preparation -- so any improvement to the documentation is welcome.

**Comment by ghost** [comment]
I updated the README

**Comment by let-def** [comment]
Which day will 4.05 be released?

I started [ppx_tools_versioned](https://github.com/let-def/ppx_tools_versioned), which is a version of [ppx_tools](https://github.com/alainfrisch/ppx_tools) built on top of ocaml-migrate-parsetree.
It would be good if that was ready for 4.05 release too.

**Comment by gasche** [comment]
@let-def we already have a ppx_tools release that works on 4.05 -- since last Sunday. A migrate-parsetree port is an excellent thing to have anyway, but it is not a blocker for the release. Outside the Jane Street world, where @diml says they should release their migrated versions soon, I think a very interesting target would be `ppx_deriving`, see https://github.com/whitequark/ppx_deriving/issues/121. I was planning on trying to do a migrate-parsetree port myself (I have the branch in my local clone) but I'm also busy with plenty of other things. Would you be willing to give it a go?

P.S.: I don't know of the release day, I'm not sure Damien has set a precise calendar yet. I will push back against releasing before we have a better picture of OPAM compatibility. Right now we need to unblock the ppx stuff, cstruct, and preferably Core before we can have some faith that most compatibility issues have been caught. (I already found two 4.05 regressions by testing Camomile.)

**Comment by let-def** [comment]
ppx_deriving issue is interesting. I will try to give it a go this week, if I have time.

Indeed my ppx_tools_versioned makes use of ppx_tools for 4.05. It just packs a migration layer on top which should ease porting. How these projects will evolve in the future, if there is place for a separate _versioned or if it should be part of ppx_tools (Alain Frisch suggested this possibility).
