### ISSUE TITLE
Compatibility with Pprintast

### ISSUE THREAD

**Issue by tekknolagi** [let-def/migrate-parsetree#12]
I would like to use `Pprintast.core_type` to stringify a core type. However, it looks like I cannot do this because of the incompatibility between ocaml-migrate-parsetree's `Parsetree` and the compiler-libs' `Parsetree`. From what I can tell, either ocaml-migrate-parsetree should implement `Pprintast`. Or is there another way to do this? Relevant code is here:

```ocaml
let string_of_core_type ( typ : Migrate_parsetree.OCaml_404.Ast.Parsetree.core_type ) =
  (* TODO: fix *)
  Format.asprintf "%a" Pprintast.core_type { typ with ptyp_attributes = [] }
```

Unrelated: where is `OCaml_OCAML_VERSION` defined?

**Comment by let-def** [comment]
1) `Pprintast` comes from compiler-libs. The idea is to migrate the type just before printing:
For instance:
```ocaml
let migrate = Versions.migrate (module OCaml_404) (module OCaml_current)

let string_of_core_type typ =
  Format.asprintf "%a" Pprintast.core_type
    (migrate.Versions.copy_core_type { typ with ptyp_attributes = [] })
```

2) OCaml_OCAML_VERSION is substituted by `pp.sh` at compile time.

**Comment by tekknolagi** [comment]
Ah, I see. Thanks!
