### ISSUE TITLE
4.06/trunk support

### ISSUE THREAD

**Issue by hhugo** [let-def/migrate-parsetree#19]

**Comment by let-def** [comment]
I just pushed trunk support. Tell me if it works for you.

**Comment by aantron** [comment]
I believe OMP was working on 4.06+trunk for a while. However, we now [get](https://travis-ci.org/ocsigen/lwt/jobs/256376561#L643):

```
File "src/ast_406.ml", line 556, characters 2-454:
Error: This variant or record definition does not match that of type
         Parsetree.class_type_desc
       The field Pcty_open is only present in the original definition.
```

Probably caused by https://github.com/ocaml/ocaml/pull/1249 being merged into `trunk`.

**Comment by let-def** [comment]
Thanks, I just synchronized with trunk.
