### ISSUE TITLE
Handling ocaml.Types.* definitions

### ISSUE THREAD

**Issue by xguerin** [let-def/migrate-parsetree#21]
Hey there,

What would be the best way to migrate code using OCaml's `Types.*` package (http://docs.mirage.io/ocaml/Types/index.html) ?

I've looked around and that package does not seem to be exported by OMP and I have not found any existing mapper from `Types ` to `Parsetree`.

Thanks,

**Comment by let-def** [comment]
No indeed, OMP doesn't deal with types.

It is possible to make sense of a parsetree alone, but most of the time types need to be interpreted in an environment.

Maybe it is possible to provide some kind of minimal support for simple applications, but the exact scope of such a feature is unclear. What are you trying to achieve?

**Comment by xguerin** [comment]
I am porting the `ppx_import` to OMP. In short, this extension uses `Cmi_format` to load and parse cmi files, and then inject type definitions based on some rules. This module uses `Types` and the extension converts `Types` types to `Parsetree` types. 

The extension already defines some conversion methods that  use CPPO to be portable across compiler versions. What I have done so far is to isolate these functions from the core logic (which relies on Ast_403) and then copy the return values of these functions into Ast_403.

**Comment by let-def** [comment]
I will close this issue for now. Handling the type system is clearly out of scope.
