### ISSUE TITLE
Sync with ocaml/trunk

### ISSUE THREAD

**Issue by hhugo** [let-def/migrate-parsetree#26]
https://github.com/ocaml/ocaml/commit/3a49d18374fc104fcd8491dd1847a199c25571fd
https://github.com/ocaml/ocaml/commit/9dc86f84172a565c221516289eaadc7f0dad1d5e

**Comment by xclerc** [comment]
Pull request: https://github.com/ocaml-ppx/ocaml-migrate-parsetree/pull/27
