### ISSUE TITLE
Support for OCaml 4.06 features in previous versions.

### ISSUE THREAD

**Issue by let-def** [let-def/migrate-parsetree#28]
It is unclear to me how to properly port some features missing from older Asts.

In <4.06, module type substitutions only took simple identifiers as path.
4.06 supports qualified identifiers, replacing a simple string by a `Longident` in the Ast.

In a first attempt to port, I chose to parse/print Longidents:
https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/4fb61f009942128f291e516a2c6c85be1dce9d03/src/migrate_parsetree_405_406_migrate.ml#L722
https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/4fb61f009942128f291e516a2c6c85be1dce9d03/src/migrate_parsetree_406_405_migrate.ml#L732

Thinking twice the correct behavior is probably to match on the `Longident.Lident` case and throw unsupported feature exceptions for other cases.
I will implement this too, but I would be happy to have some feedback before releasing.

**Comment by yallop** [comment]
> Thinking twice the correct behavior is probably to match on the Longident.Lident case and throw unsupported feature exceptions for other cases.

Yes, that sounds reasonable to me.

**Comment by let-def** [comment]
Done.
