### ISSUE TITLE
Circular dependency problem with OPAM on Travis

### ISSUE THREAD

**Issue by xguerin** [let-def/migrate-parsetree#38]
Hello !

I ran into a bit of a problem yesterday while CI'ing a project on Travis. See: ocaml/opam#3213. OPAM is failing on the last installable step complaining about a circular dependency between OMP and jbuilder.

Interestingly I could not reproduce the problem locally. Did you guys run into something similar ?

I've cross-posted than issue on dune https://github.com/ocaml/dune/issues/492 for good measure.

x

**Comment by ghost** [comment]
I'm closing this issue as I believe it is now fixed
