### ISSUE TITLE
compat for 4.07

### ISSUE THREAD

**Issue by hhugo** [let-def/migrate-parsetree#42]

**Comment by ghost** [comment]
So the latest released version of omp does work with 4.07, however ocamlfind is currently not installable on 4.07, so omp can't be installed on 4.07.

@yunxing, do you still care about omp having a dependency on ocamlfind? omp doesn't need ocamlfind, so it would be better to drop this dependency.

**Comment by let-def** [comment]
I just pushed 4.07 support.

**Comment by let-def** [comment]
@diml: I could have done a pull request... I can revert if you feel uneasy about that. In any case, your feedback about the patch is welcome.

**Comment by hhugo** [comment]
Thanks

**Comment by ghost** [comment]
@let-def that's ok, I had a look and have no comment. But thanks for letting me know, I don't follow commits to master, only PRs
