### ISSUE TITLE
Parsetree.effect_constructor missing build failure...

### ISSUE THREAD

**Issue by houndofsound** [let-def/migrate-parsetree#48]
I have OMP installed via opam under 4.06.1
but I'm getting the "I can't decide ...." error when trying to use core so I went to compile the OMP source in order then to make the necessary adjustment (I cannot upgrade).
but I'm getting a an error as per the title.
I looked in ocaml 4.07 sources for that and it isn't even there!
this is confusing. anyone know what's going on?
thanks

**Comment by hhugo** [comment]
The constructor belongs to ocaml multicore.

**Comment by hhugo** [comment]
I believe this can be closed.
