### ISSUE TITLE
Wish: support migration of Env

### ISSUE THREAD

**Issue by gpetiot** [let-def/migrate-parsetree#54]
Would it be difficult to handle the migrations of env.ml ? I am mainly interested by the migration between 4.06 and 4.07 where the type `Env.summary` has been changed.
Thanks.

**Comment by let-def** [comment]
I think ocaml-migrate-parsetree should only handle migration of purely syntactic objects, while environments and typedtrees are richer than that. It is not clear what it would mean to migrate those.

So omp is not the right place for that in my opinion. However, defining a relatively portable abstraction over compiler-libs is an interesting project. I don't know how that would be done but it is the right time for gathering requirements.
