### ISSUE TITLE
Ability to read any version of AST

### ISSUE THREAD

**Issue by aantron** [let-def/migrate-parsetree#78]
It would be useful for [Bisect_ppx](https://github.com/aantron/bisect_ppx#readme) compiled on any OCaml version, to be able to read and write ASTs produced by any other OCaml version.

I think this is a sort of dual of current OMP functionality.

The context is that Bisect_ppx is now [ported](https://github.com/aantron/bisect_ppx#BuckleScript) to BuckleScript, but during installation, BuckleScript is an NPM peer dependency of Bisect_ppx. This means that we can't guarantee that BuckleScript is installed first, so we can't detect its OCaml version number and use it for compiling the Bisect PPX with the same OCaml compiler. The current workaround for this is to constrain both the BuckleScript version and the OCaml version very specifically.

Ideally, we could generate one PPX, no matter which compiler compiled it, that can read any AST that is so far supported by OMP.

**Comment by aantron** [comment]
Looks like OMP already has machinery for this. Looking into whether this issue is valid.

**Comment by let-def** [comment]
Yes, the [Ast_io](https://github.com/ocaml-ppx/ocaml-migrate-parsetree/blob/master/src/migrate_parsetree_ast_io.mli) module is doing just that.

**Comment by aantron** [comment]
The issue is that it's not being used in `--as-ppx` mode. I am switching to running the PPX as a standalone driver, but it looks like there will be other issues resulting from that.
