### ISSUE TITLE
support for upcoming OCaml 4.10 ?

### ISSUE THREAD

**Issue by gasche** [let-def/migrate-parsetree#85]
As of this week, the versions of ocaml-migrate-parsetree available on opam are incompatible (or at least marked incompatible) with the upcoming 4.10 release. Would it be possible to ensure compatibility with the current 4.10 branch, and have a version available on opam that enables it, or at least a clear reference to pin? This would unlock testing of user code when we make our first beta releases (expected in a few weeks).

(We do not *expect* to change the parsetree now that the release branch has been created, but there is a small chance that it could happen, for example thanks to m-o-p dogfooding the changes and suggesting fixes. I still think having an opam release is nicer than pinning, especially for people doing release Q/A with opam testing tools.)

Thanks!

**Comment by gasche** [comment]
(cc @Octachron @damiendoligez @kit-ty-kate)

**Comment by ghost** [comment]
Let me have a look at this. What's the recommended way of installing a non-released compiler nowadays?

**Comment by gasche** [comment]
It's documented in the compiler's HACKING.adoc file:

```
opam switch create . --empty
opam install .
```

**Comment by ghost** [comment]
The magic numbers for the AST ends with 26 in 4.09 and with 25 in 4.10. That looks ood

**Comment by gasche** [comment]
It may be very well be that the magic numbers have not been updated in 4.10 yet. Let me check with @damiendoligez, thanks for the feedback!

**Comment by gasche** [comment]
Yes! @Octachron volunteered to update magic numbers in 4.10 and trunk, should be done shortly.

**Comment by Octachron** [comment]
The magic numbers have updated (and end with 27), on both 4.10 and trunk (to avoid trunk trailing with the magic number of 4.08).

**Comment by ghost** [comment]
I updated ocaml-migrate-parsetree to 4.10. Release is pending on this: https://github.com/samoht/dune-release/issues/174

**Comment by ghost** [comment]
it's now released: https://github.com/ocaml/opam-repository/pull/15280
