### ISSUE TITLE
Could not build Tezos node which depends on ocaml-migrate-parsetree

### ISSUE THREAD

**Issue by dimaa6** [let-def/migrate-parsetree#87]
[ERROR] The sources of the following couldn't be obtained, aborting:
          - ocaml-migrate-parsetree.1.4.0: Bad checksum

**Comment by rmn30** [comment]
I also have this error. Looking at the metadata for release 1.4.0 in the [opam-repository](https://github.com/ocaml/opam-repository/commits/master/packages/ocaml-migrate-parsetree/ocaml-migrate-parsetree.1.4.0/opam) it looks like the release is from July 2019 but the [v1.4.0 tag](https://github.com/ocaml-ppx/ocaml-migrate-parsetree/releases/tag/v1.4.0) was made very recently by @diml . Maybe the tag was moved by mistake?

As a workaround I was able to install 1.3.1 using:
```
opam pin ocaml-migrate-parsetree 1.3.1
```
which was sufficient for me to install the package I wanted.

**Comment by lindig** [comment]
it is somewhat curious that a large number of packages in Opam seem to have broken checksums.

https://github.com/ocaml/opam-repository/issues/15298

A typical reason is that a file hosted by GitHub is re-compressed, which changes the checksum. Many of the affected packages are not hosted on GitHub, though. The current issue here is different: the source code actually changed.

**Comment by P3tronius** [comment]
You can also force install 1.4.0 using `opam install ocaml-migrate-parsetree  --no-checksums` and the resume tezos's `make build-deps`

**Comment by mseri** [comment]
Omp 1.4.0 has been fixed later yesterday (https://github.com/ocaml/opam-repository/issues/15281). I recommend not to use —no-checkums, in this case the tarball was changed by mistake and you would have installed a different library version than expected. In general it is safer to revert to the previous version with correct checksum as suggested by @rmn30

**Comment by ghost** [comment]
So in the end what happened is that I messed up and accidentally replaced the 1.4.0 tarball in place on github (cf https://github.com/ocaml/opam-repository/pull/15280#issuecomment-554959337). The original tarball has now been restored on ocaml-ppx/ocaml-migrate-parsetree as well as the original checksum in the opam-repository. So all is good now.
