### ISSUE TITLE
failures in ppx_deriving after upgrade from 1.5.0 to 1.6.0

### ISSUE THREAD

**Issue by olafhering** [let-def/migrate-parsetree#90]
[ocaml-migrate-parsetree](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-migrate-parsetree) was upgraded from v1.5.0 to v1.6.0. All packages which depend on this package were rebuilt automatically. For some reason [ocaml-ppx_deriving](https://build.opensuse.org/package/show/devel:languages:ocaml/ocaml-ppx_deriving) now fails to build. It runs `ppxfind -legacy`, which is now "suddenly" an unknown cmdline option.

I reverted back to v1.5.0 get the prj [devel:languages:ocaml](https://build.opensuse.org/project/show/devel:languages:ocaml) back into state `succeeded`. The build log of `ppx_deriving` indicates `ppxfind -legacy` is working, Not sure how `migrate-parsetree` influences the behavior of `ppx_deriving`

**Comment by aantron** [comment]
@olafhering See https://github.com/ocaml/opam-repository/pull/15821 and all the linked PRs, including https://github.com/ocaml/opam-repository/pull/15830 and https://github.com/diml/ppxfind/pull/6. OMP 1.6.0 broke ppxfind (unexpectedly, at least for me), so the new release 1.4 of ppxfind is required to work with it.

**Comment by olafhering** [comment]
Yes, I have seen the new ppxfind package, it fixed the build error.
